load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

cc_library(
    name = "binary_tree",
    srcs = ["binary_tree.hpp"],
)

cc_library(
    name = "binary_search_tree",
    srcs = ["binary_search_tree.hpp"],
)

cc_library(
    name = "rbtree",
    srcs = ["rbtree.hpp"],
)